#!/usr/bin/env bash

# This file is to save the last session name
temp_data="/tmp/tmux-sessionizer_last_session"

# If there is only one argument and it is 'last_session', then use the last session
if [[ $# -eq 1 ]]; then
    if [[ $1 == 'last_session' ]]; then
        selected=$(cat $temp_data)
    else
		target_dir=""

        # Check if the path itself is the worktree/git dir
        if [[ -d "$1/worktrees" || -d "$1/objects" ]]; then
            target_dir="$1"
        # Check if the parent of the path is the worktree/git dir
        elif [[ -d "$1/../worktrees" || -d "$1/../objects" ]]; then
            target_dir=$(realpath "$1/..")
        fi

        if [[ -n "$target_dir" ]]; then
            selected=$(find "$target_dir" -mindepth 1 -maxdepth 1 -type d \
                -not -name "hooks" \
                -not -name "info" \
                -not -name "objects" \
                -not -name "refs" \
                -not -name "logs" \
                -not -name "worktrees" | fzf)
        else
            # Not a worktree directory or child of one; do nothing
            exit 0
        fi
    fi
else
    selected=$(find ~ ~/personal ~/work ~/plugins -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

# Save the current session name
current_session=$(tmux display-message -p '#S')
echo $current_session > $temp_data

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name

