#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
dry="0"
cleanup="0"

while [[ $# > 0 ]]; do
	if [[ $1 == "--dry" ]]; then
		dry="1"
	fi

	if [[ $1 == "--cleanup" ]]; then
		cleanup="1"
	fi

	shift
done

echo $cleanup

log() {
	if [[ $dry == "1" ]]; then
		echo "[DRY_RUN]: $@"
	else
		echo "$@"
	fi
}

execute() {
	log "execute $@"
	if [[ $dry == "1" ]]; then
		return
	fi
	"$@"
}

log "------------------ dev --------------------"

copy_dir() {
	from=$1
	to=$2

	pushd $from > /dev/null
		dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
		for dir in $dirs; do
			execute rm -rf $to/$dir
			if [[ $cleanup != "1" ]]; then
				execute cp -r $dir $to/$dir
			fi
		done
	popd > /dev/null
}

copy_dir_files() {
	from=$1
	to=$2

	pushd $from > /dev/null
		files=$(find . -mindepth 1 -maxdepth 1 -type f)
		for file in $files; do
			execute rm $to/$file
			if [[ $cleanup != "1" ]]; then
				execute cp $file $to/$file
			fi
		done
	popd > /dev/null
}

copy_file() {
	from=$1
	to=$2
	name=$(basename $from)

	execute rm $to/$name
	if [[ $cleanup != "1" ]]; then
		execute cp $from $to/$name
	fi
}

copy_dir config $HOME/.config
copy_dir local $HOME/.local
copy_dir_files config $HOME/.config
copy_dir_files home $HOME

if [[ "$(uname -s)" == "Linux" ]]; then
	copy_dir linux_config $HOME/.config
fi
