#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
        STOW_FOLDERS="zsh,other,tmux,alacritty,starship,bin"
        STOW_LINUX="i3"
        STOW_MAC=""
    if [[ $(uname) != "Darwin" ]]; then
        STOW_FOLDERS+=$STOW_LINUX
    elif [[ $(uname) == "Darwin" ]]; then
        STOW_FOLDERS+=$STOW_MAC
    fi
fi

echo $STOW_FOLDERS

###
### CHANGE THIS LOCATION
###
if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dot
fi

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder --adopt
done
popd
