#!/bin/bash

rm -rf ~/.config/kitty
rm -rf ~/.config/nvim
rm -rf ~/.config/phpactor
rm -rf ~/.config/i3
rm -rf ~/.config/i3status
rm -rf ~/.scripts
rm -rf ~/.hushlogin
rm -rf ~/.zsh_aliases
rm -rf ~/.zshrc
rm -rf ~/.tmux.conf

stow .
