#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source "$script_dir/init.sh"

core_setup_linux() {
	sudo pacman -Syu
	sudo pacman -S tmux fish starship
}

core_setup_mac() {
	brew install tmux fish starship
}

# [ Update ]
if is_linux; then
	core_setup_linux()
else
	core_setup_mac()
fi

if ! command -v rustup >/dev/null 2>&1; then
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

chsh -s $(which fish)
