#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source "$script_dir/init.sh"

linux() {
	sudo pacman -Syu
	sudo pacman -S neovim
}

mac() {
	brew install neovim
}

# [ Update ]
if is_linux; then
	linux()
else
	mac()
fi

git clone -b main https://github.com/azatakmyradov/nvim $HOME/personal/nvim
