#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
source "$script_dir/init.sh"

linux() {
	paru -S ghostty helium-browser-bin
}

mac() {
	brew install --cask ghostty
	brew install --cask helium-browser
}

# [ Update ]
if is_linux; then
	linux()
else
	mac()
fi
